### ISSUE TITLE
Not rendering in chrome for iOS

### ISSUE THREAD

**Issue by ottonascarella** [codepo8/canvas-masking#1]
Hi there,

I don't know why it is not rendering on Chorme for iOS.
Certainly issues with browser.
Browser version: 27.0.1453.10

Just thought you'd be interested to know.

Cheers,

**Comment by codepo8** [comment]
Does it work in Safari in iOS? On Safari Desktop it works, and on Chrome/Firefox on Android

**Comment by ottonascarella** [comment]
Yep. It works on latest Safari for iOS 6.something

Haven't tested it on Chrome for Android

**Comment by codepo8** [comment]
Browser issue, I guess :(
