### ISSUE TITLE
Great script! Supposed to work in IE? Probably not?

### ISSUE THREAD

**Issue by silentdan** [codepo8/canvas-masking#3]
Just wondering, script supposed to work with < IE9?
I tried to bundle this with https://code.google.com/p/explorercanvas/, but can't get it out of the box too work. so it comes down with IE it seems to @derschepp approach:http://thenittygritty.co/css-masking ?
thank you very much, chris!

update: border-radius does the job!

**Comment by bfintal** [comment]
Doubt it since the canvas element isn't supported < ie9 (and the current opera mini also for that matter): http://caniuse.com/#search=canvas

**Comment by codepo8** [comment]
yep, no canvas in OldIE :(
