### ISSUE TITLE
responsive mask

### ISSUE THREAD

**Issue by markosansa** [codepo8/canvas-masking#4]
Is it possible to create a responsive mask with this ?

thank you so much!

**Comment by dilrajahdan** [comment]
it is already responsive. just add min-width or max-width to your image.

**Comment by markosansa** [comment]
Great!!!! Thank you so much!!!!

**Comment by dilrajahdan** [comment]
no probs

**Comment by codepo8** [comment]
Cheers dilrajahdan!
